name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, research/*, feat/* ]

jobs:
  run-tests:
    name: Run Unit Tests
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v5

      - name: 🐍 Install uv and set Python version ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v7.1.1
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: 📦 Install System Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1

      - name: 🚀 Install Packages
        run: uv sync --extra cpu --locked

      - name: 🧪 Run the Tests
        run: uv run pytest tests/ -v